import MainLayout from "@/components/layouts/main";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Example For Post Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <MainLayout>{children}</MainLayout>;
}
